### Start here

In [1]:
import os
import json
from pathlib import Path
import pandas as pd
import glob
import numpy as np

target_dir = Path.cwd().parent / 'csv' / '_processed'
export_dir = Path.cwd().parent / 'csv' / '_fromPandas'
csvs = glob.glob(os.path.join(target_dir, "*classified.csv"))

df_list = []
for csv in csvs:
    df_list.append(pd.read_csv(csv))
len(df_list)

df = pd.concat(df_list, ignore_index=True)
df

,index,author,url,recipeTitle,recipeRating,commentBody,commentType,userID,commentRecommendations,prompt,ai_guess
0,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),Delicious! I would suggest maybe letting the m...,comment,15548414,325,\n\nHere's a comment from NYT Cooking:Deliciou...,thinks_recipe_is_flawed_due_to_technique_or_eq...
1,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),"I cooked the brisket, with all the Bulgogi ing...",comment,71133436,137,\n\nHere's a comment from NYT Cooking:I cooked...,positive_user_describing_changes
2,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),I used flank steak b/c the Wegman's I went to ...,comment,57060720,70,\n\nHere's a comment from NYT Cooking:I used f...,positive_user_describing_changes
3,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),"For my vegetarian household, I substituted sei...",comment,65782933,62,\n\nHere's a comment from NYT Cooking:For my v...,positive_user_describing_changes
4,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),Put the whole piece of brisket in the freezer ...,comment,72381463,46,\n\nHere's a comment from NYT Cooking:Put the ...,maybe_not_about_the_recipe
...,...,...,...,...,...,...,...,...,...,...,...
76717,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),Froze half after shaping before the last proof...,comment,232304210,0,\n\nHere's a comment from NYT Cooking:Froze ha...,positive_user_describing_changes
76718,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),Thank you Claire. I’m on my 6 try at perfectin...,comment,176541269,0,\n\nHere's a comment from NYT Cooking:Thank yo...,positive_user_made_as_written
76719,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),This turned out so well!! For the final proof ...,comment,224292953,0,\n\nHere's a comment from NYT Cooking:This tur...,positive_user_describing_changes
76720,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),First time attempting a puff pastry and it tur...,comment,72466649,0,\n\nHere's a comment from NYT Cooking:First ti...,positive_user_made_as_written
76721,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),These are delicious! They have come out perfec...,comment,59884695,0,\n\nHere's a comment from NYT Cooking:These ar...,positive_user_describing_changes

### [DATA CLEANING] Filter for approved authors

In [2]:
authors_json = Path.cwd().parent / 'json' / '_for-scraping' / 'recipe_links_by_author.json'

with open(authors_json, 'r') as file:
    data = json.load(file)

authors = list(data.keys())

df = df[df['author'].isin(authors)]
df

,index,author,url,recipeTitle,recipeRating,commentBody,commentType,userID,commentRecommendations,prompt,ai_guess
0,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),Delicious! I would suggest maybe letting the m...,comment,15548414,325,\n\nHere's a comment from NYT Cooking:Deliciou...,thinks_recipe_is_flawed_due_to_technique_or_eq...
1,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),"I cooked the brisket, with all the Bulgogi ing...",comment,71133436,137,\n\nHere's a comment from NYT Cooking:I cooked...,positive_user_describing_changes
2,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),I used flank steak b/c the Wegman's I went to ...,comment,57060720,70,\n\nHere's a comment from NYT Cooking:I used f...,positive_user_describing_changes
3,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),"For my vegetarian household, I substituted sei...",comment,65782933,62,\n\nHere's a comment from NYT Cooking:For my v...,positive_user_describing_changes
4,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,5(791),Put the whole piece of brisket in the freezer ...,comment,72381463,46,\n\nHere's a comment from NYT Cooking:Put the ...,maybe_not_about_the_recipe
...,...,...,...,...,...,...,...,...,...,...,...
76717,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),Froze half after shaping before the last proof...,comment,232304210,0,\n\nHere's a comment from NYT Cooking:Froze ha...,positive_user_describing_changes
76718,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),Thank you Claire. I’m on my 6 try at perfectin...,comment,176541269,0,\n\nHere's a comment from NYT Cooking:Thank yo...,positive_user_made_as_written
76719,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),This turned out so well!! For the final proof ...,comment,224292953,0,\n\nHere's a comment from NYT Cooking:This tur...,positive_user_describing_changes
76720,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),First time attempting a puff pastry and it tur...,comment,72466649,0,\n\nHere's a comment from NYT Cooking:First ti...,positive_user_made_as_written
76721,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,5(335),These are delicious! They have come out perfec...,comment,59884695,0,\n\nHere's a comment from NYT Cooking:These ar...,positive_user_describing_changes

### [DATA CLEANING] Separate rating from number of ratings

In [3]:
df['recipeScore'] = df['recipeRating'].str.extract(r'([\d,.]+)[^(]*\(')
df['numberOfRatings'] = df['recipeRating'].str.extract(r'\(([\d,.]+)')
df = df.drop(columns='recipeRating')
df

,index,author,url,recipeTitle,commentBody,commentType,userID,commentRecommendations,prompt,ai_guess,recipeScore,numberOfRatings
0,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Delicious! I would suggest maybe letting the m...,comment,15548414,325,\n\nHere's a comment from NYT Cooking:Deliciou...,thinks_recipe_is_flawed_due_to_technique_or_eq...,5,791
1,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"I cooked the brisket, with all the Bulgogi ing...",comment,71133436,137,\n\nHere's a comment from NYT Cooking:I cooked...,positive_user_describing_changes,5,791
2,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,I used flank steak b/c the Wegman's I went to ...,comment,57060720,70,\n\nHere's a comment from NYT Cooking:I used f...,positive_user_describing_changes,5,791
3,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"For my vegetarian household, I substituted sei...",comment,65782933,62,\n\nHere's a comment from NYT Cooking:For my v...,positive_user_describing_changes,5,791
4,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Put the whole piece of brisket in the freezer ...,comment,72381463,46,\n\nHere's a comment from NYT Cooking:Put the ...,maybe_not_about_the_recipe,5,791
...,...,...,...,...,...,...,...,...,...,...,...,...
76717,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Froze half after shaping before the last proof...,comment,232304210,0,\n\nHere's a comment from NYT Cooking:Froze ha...,positive_user_describing_changes,5,335
76718,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Thank you Claire. I’m on my 6 try at perfectin...,comment,176541269,0,\n\nHere's a comment from NYT Cooking:Thank yo...,positive_user_made_as_written,5,335
76719,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,This turned out so well!! For the final proof ...,comment,224292953,0,\n\nHere's a comment from NYT Cooking:This tur...,positive_user_describing_changes,5,335
76720,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,First time attempting a puff pastry and it tur...,comment,72466649,0,\n\nHere's a comment from NYT Cooking:First ti...,positive_user_made_as_written,5,335
76721,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,These are delicious! They have come out perfec...,comment,59884695,0,\n\nHere's a comment from NYT Cooking:These ar...,positive_user_describing_changes,5,335

### [DATA CLEANING] Adding sentiment column from map

In [4]:
sentiment_map = {
    "positive_user_made_as_written" : "positive",
    "positive_user_describing_changes" : "positive",
    "thinks_recipe_is_flawed_due_to_flavor" : "negative",
    "thinks_recipe_is_flawed_due_to_technique_or_equipment" : "negative",
    "thinks_recipe_is_flawed_due_to_cooking_time" : "negative",
    "thinks_recipe_is_inauthentic" : "negative",
    "thinks_ingredients_hard_to_find" : "negative",
    "user_responding_to_other_user" : "neutral",
    "question" : "neutral",
    "maybe_not_about_the_recipe" : "neutral"
}

df['sentiment'] = df['ai_guess'].map(sentiment_map)
df

,index,author,url,recipeTitle,commentBody,commentType,userID,commentRecommendations,prompt,ai_guess,recipeScore,numberOfRatings,sentiment
0,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Delicious! I would suggest maybe letting the m...,comment,15548414,325,\n\nHere's a comment from NYT Cooking:Deliciou...,thinks_recipe_is_flawed_due_to_technique_or_eq...,5,791,negative
1,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"I cooked the brisket, with all the Bulgogi ing...",comment,71133436,137,\n\nHere's a comment from NYT Cooking:I cooked...,positive_user_describing_changes,5,791,positive
2,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,I used flank steak b/c the Wegman's I went to ...,comment,57060720,70,\n\nHere's a comment from NYT Cooking:I used f...,positive_user_describing_changes,5,791,positive
3,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"For my vegetarian household, I substituted sei...",comment,65782933,62,\n\nHere's a comment from NYT Cooking:For my v...,positive_user_describing_changes,5,791,positive
4,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Put the whole piece of brisket in the freezer ...,comment,72381463,46,\n\nHere's a comment from NYT Cooking:Put the ...,maybe_not_about_the_recipe,5,791,neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76717,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Froze half after shaping before the last proof...,comment,232304210,0,\n\nHere's a comment from NYT Cooking:Froze ha...,positive_user_describing_changes,5,335,positive
76718,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Thank you Claire. I’m on my 6 try at perfectin...,comment,176541269,0,\n\nHere's a comment from NYT Cooking:Thank yo...,positive_user_made_as_written,5,335,positive
76719,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,This turned out so well!! For the final proof ...,comment,224292953,0,\n\nHere's a comment from NYT Cooking:This tur...,positive_user_describing_changes,5,335,positive
76720,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,First time attempting a puff pastry and it tur...,comment,72466649,0,\n\nHere's a comment from NYT Cooking:First ti...,positive_user_made_as_written,5,335,positive
76721,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,These are delicious! They have come out perfec...,comment,59884695,0,\n\nHere's a comment from NYT Cooking:These ar...,positive_user_describing_changes,5,335,positive

### [DATA CLEANING] Adding readable ai guess column

In [5]:
readable_categories_map = {
    "positive_user_made_as_written" : "Liked recipe and prepared as written",
    "positive_user_describing_changes" : "Liked recipe but made changes",
    "thinks_recipe_is_flawed_due_to_flavor" : "Didn't like recipe due to flavor",
    "thinks_recipe_is_flawed_due_to_technique_or_equipment" : "Didn't like recipe due to technique or equipment",
    "thinks_recipe_is_flawed_due_to_cooking_time" : "Thought the cooking times were wrong",
    "thinks_recipe_is_inauthentic" : "Thought the recipe was inauthentic",
    "thinks_ingredients_hard_to_find" : "Thought ingredients were hard to find",
    "user_responding_to_other_user" : "Commenter responding to other commenter",
    "question" : "Commenter asking a question",
    "maybe_not_about_the_recipe" : "Off-topic"
}

df['readable_ai_guess'] = df['ai_guess'].map(readable_categories_map)
df

,index,author,url,recipeTitle,commentBody,commentType,userID,commentRecommendations,prompt,ai_guess,recipeScore,numberOfRatings,sentiment,readable_ai_guess
0,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Delicious! I would suggest maybe letting the m...,comment,15548414,325,\n\nHere's a comment from NYT Cooking:Deliciou...,thinks_recipe_is_flawed_due_to_technique_or_eq...,5,791,negative,Didn't like recipe due to technique or equipment
1,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"I cooked the brisket, with all the Bulgogi ing...",comment,71133436,137,\n\nHere's a comment from NYT Cooking:I cooked...,positive_user_describing_changes,5,791,positive,Liked recipe but made changes
2,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,I used flank steak b/c the Wegman's I went to ...,comment,57060720,70,\n\nHere's a comment from NYT Cooking:I used f...,positive_user_describing_changes,5,791,positive,Liked recipe but made changes
3,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"For my vegetarian household, I substituted sei...",comment,65782933,62,\n\nHere's a comment from NYT Cooking:For my v...,positive_user_describing_changes,5,791,positive,Liked recipe but made changes
4,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Put the whole piece of brisket in the freezer ...,comment,72381463,46,\n\nHere's a comment from NYT Cooking:Put the ...,maybe_not_about_the_recipe,5,791,neutral,Off-topic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76717,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Froze half after shaping before the last proof...,comment,232304210,0,\n\nHere's a comment from NYT Cooking:Froze ha...,positive_user_describing_changes,5,335,positive,Liked recipe but made changes
76718,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Thank you Claire. I’m on my 6 try at perfectin...,comment,176541269,0,\n\nHere's a comment from NYT Cooking:Thank yo...,positive_user_made_as_written,5,335,positive,Liked recipe and prepared as written
76719,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,This turned out so well!! For the final proof ...,comment,224292953,0,\n\nHere's a comment from NYT Cooking:This tur...,positive_user_describing_changes,5,335,positive,Liked recipe but made changes
76720,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,First time attempting a puff pastry and it tur...,comment,72466649,0,\n\nHere's a comment from NYT Cooking:First ti...,positive_user_made_as_written,5,335,positive,Liked recipe and prepared as written
76721,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,These are delicious! They have come out perfec...,comment,59884695,0,\n\nHere's a comment from NYT Cooking:These ar...,positive_user_describing_changes,5,335,positive,Liked recipe but made changes

### [DATA CLEANING] Dropping prompt column

In [6]:
df = df.drop(columns = 'prompt')

In [98]:
df

,index,author,url,recipeTitle,commentBody,commentType,userID,commentRecommendations,ai_guess,recipeScore,numberOfRatings,sentiment,readable_ai_guess
0,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Delicious! I would suggest maybe letting the m...,comment,15548414,325,thinks_recipe_is_flawed_due_to_technique_or_eq...,5,791,negative,Didn't like recipe due to technique or equipment
1,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"I cooked the brisket, with all the Bulgogi ing...",comment,71133436,137,positive_user_describing_changes,5,791,positive,Liked recipe but made changes
2,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,I used flank steak b/c the Wegman's I went to ...,comment,57060720,70,positive_user_describing_changes,5,791,positive,Liked recipe but made changes
3,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"For my vegetarian household, I substituted sei...",comment,65782933,62,positive_user_describing_changes,5,791,positive,Liked recipe but made changes
4,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Put the whole piece of brisket in the freezer ...,comment,72381463,46,maybe_not_about_the_recipe,5,791,neutral,Off-topic
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76717,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Froze half after shaping before the last proof...,comment,232304210,0,positive_user_describing_changes,5,335,positive,Liked recipe but made changes
76718,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Thank you Claire. I’m on my 6 try at perfectin...,comment,176541269,0,positive_user_made_as_written,5,335,positive,Liked recipe and prepared as written
76719,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,This turned out so well!! For the final proof ...,comment,224292953,0,positive_user_describing_changes,5,335,positive,Liked recipe but made changes
76720,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,First time attempting a puff pastry and it tur...,comment,72466649,0,positive_user_made_as_written,5,335,positive,Liked recipe and prepared as written
76721,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,These are delicious! They have come out perfec...,comment,59884695,0,positive_user_describing_changes,5,335,positive,Liked recipe but made changes

### (df) Positive vs negative comments total:

In [8]:
df_comment_totals_by_category = df['ai_guess'].value_counts().reset_index()
df_comment_totals_by_category

                                            ai_guess  count
0                   positive_user_describing_changes  37275
1                                           question  11090
2                      positive_user_made_as_written   7837
3  thinks_recipe_is_flawed_due_to_technique_or_eq...   5373
4              thinks_recipe_is_flawed_due_to_flavor   5245
5                         maybe_not_about_the_recipe   3976
6        thinks_recipe_is_flawed_due_to_cooking_time   2229
7                      user_responding_to_other_user   2218
8                       thinks_recipe_is_inauthentic    760
9                    thinks_ingredients_hard_to_find    719

In [9]:
df_comment_totals_by_category.to_csv(os.path.join(export_dir, "df_comment_totals_by_category.csv"), index=False)

In [10]:
df_comment_totals_by_sentiment = df['ai_guess'].map(sentiment_map).value_counts(normalize=True)
# df_comment_totals_by_sentiment = df_comment_totals_by_sentiment.reset_index()
# df_comment_totals_by_sentiment
df_comment_totals_by_sentiment

ai_guess
positive    0.587993
neutral     0.225281
negative    0.186726
Name: proportion, dtype: float64

In [11]:
df_negative_comments = df.query('sentiment == "negative"')
df_negative_comments['ai_guess'].value_counts(normalize=True)

ai_guess
thinks_recipe_is_flawed_due_to_technique_or_equipment    0.375052
thinks_recipe_is_flawed_due_to_flavor                    0.366118
thinks_recipe_is_flawed_due_to_cooking_time              0.155591
thinks_recipe_is_inauthentic                             0.053050
thinks_ingredients_hard_to_find                          0.050188
Name: proportion, dtype: float64

### (df) Total number of comments:

### (df) Top comments:

In [12]:
df_top_comments = df.sort_values('commentRecommendations', ascending = False).head(100)
df_top_comments

,index,author,url,recipeTitle,commentBody,commentType,userID,commentRecommendations,ai_guess,recipeScore,numberOfRatings,sentiment,readable_ai_guess
57771,15,Priya Krishna,https://cooking.nytimes.com/recipes/1020728-ho...,Homemade Hamburger Helper Recipe,I got drunk and made this when my fiancee wasn...,comment,77885759,2513,positive_user_made_as_written,4,"9,957",positive,Liked recipe and prepared as written
17523,6,Ligaya Mishan,https://cooking.nytimes.com/recipes/1026314-ya...,Yamitsuki (Addictive Cabbage) Recipe,This is Lisa Kyung Gross--founder of the Leagu...,comment,58439572,2216,user_responding_to_other_user,4,"1,985",neutral,Commenter responding to other commenter
53849,16,Yotam Ottolenghi,https://cooking.nytimes.com/recipes/1026583-ch...,Chicken and Chickpea Tray Bake Recipe,Ras El hanout recipe: \n\n1 teaspoon salt\n\n1...,comment,83864368,2115,maybe_not_about_the_recipe,5,"3,172",neutral,Off-topic
4404,25,Sam Sifton,https://cooking.nytimes.com/recipes/9558-takeo...,Takeout-Style Sesame Noodles Recipe,I learned how to make a version of this from a...,comment,930376,2054,positive_user_describing_changes,5,"12,461",positive,Liked recipe but made changes
64479,19,Alexa Weibel,https://cooking.nytimes.com/recipes/1025325-cr...,"Creamy, Spicy Tomato Beans and Greens Recipe",To make this vegan:\nI used a can of coconut c...,comment,87430575,2023,positive_user_describing_changes,5,"12,771",positive,Liked recipe but made changes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39457,24,Genevieve Ko,https://cooking.nytimes.com/recipes/1026644-oa...,Eggless Pancake Recipe,A couple of additional tips. When cooking panc...,comment,48489584,575,positive_user_describing_changes,5,"1,406",positive,Liked recipe but made changes
49824,11,Eric Kim,https://cooking.nytimes.com/recipes/1027633-sp...,Spinach Egg Bites Recipe,"I make egg bites all the time, and they used t...",comment,122580326,571,positive_user_describing_changes,5,"1,856",positive,Liked recipe but made changes
66841,36,Alexa Weibel,https://cooking.nytimes.com/recipes/1024062-ro...,Roasted White Bean and Tomato Pasta Recipe,"Thanks! A lovely dish, pasta e fagioli always ...",comment,202860814,570,thinks_recipe_is_inauthentic,5,"4,522",negative,Thought the recipe was inauthentic
39787,26,Genevieve Ko,https://cooking.nytimes.com/recipes/1026551-sp...,"Spicy, Creamy Weeknight Bolognese Recipe","Is this Thai red curry paste, asks a reader in...",comment,86751355,566,question,5,"5,822",neutral,Commenter asking a question
8727,20,Vaughn Vreeland,https://cooking.nytimes.com/recipes/1026584-tr...,Triple-Chocolate Brownies Recipe,I’m 11 years old and just baked this recipe as...,comment,61149609,560,positive_user_describing_changes,5,503,positive,Liked recipe but made changes

In [13]:
df_top_comment_category_totals = df_top_comments['ai_guess'].value_counts().reset_index()
df_top_comment_category_totals

                                            ai_guess  count
0                   positive_user_describing_changes     58
1                         maybe_not_about_the_recipe     13
2  thinks_recipe_is_flawed_due_to_technique_or_eq...     10
3                      user_responding_to_other_user      5
4                                           question      4
5                      positive_user_made_as_written      3
6        thinks_recipe_is_flawed_due_to_cooking_time      3
7                       thinks_recipe_is_inauthentic      2
8                    thinks_ingredients_hard_to_find      1
9              thinks_recipe_is_flawed_due_to_flavor      1

In [14]:
df_top_comment_category_totals.to_csv(os.path.join(export_dir, "df_top_comment_category_totals.csv"), index=False)

In [15]:
df_top_comments.to_csv(os.path.join(export_dir, "df_top_comments.csv"), index=False)

In [16]:
df.shape

(76722, 13)

### (df_commenters) Commenters

In [17]:
df_comment_recs = df.groupby('userID')['commentRecommendations'].sum()
df_comment_recs

userID
0             1
1012          0
1016          1
2440          0
2622         38
             ..
314458268     0
314502650     0
314699740     2
314847038     0
315937775     0
Name: commentRecommendations, Length: 54886, dtype: int64

In [76]:
df_commenters = df.groupby('userID')['ai_guess'].value_counts().unstack().fillna(0)
df_commenters

ai_guess,maybe_not_about_the_recipe,positive_user_describing_changes,positive_user_made_as_written,question,thinks_ingredients_hard_to_find,thinks_recipe_is_flawed_due_to_cooking_time,thinks_recipe_is_flawed_due_to_flavor,thinks_recipe_is_flawed_due_to_technique_or_equipment,thinks_recipe_is_inauthentic,user_responding_to_other_user
userID,,,,,,,,,,
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1012,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1016,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2440,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2622,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
314458268,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
314502650,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
314699740,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
314847038,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
315937775,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
positive = ['positive_user_made_as_written', 'positive_user_describing_changes']
negative = ['thinks_recipe_is_flawed_due_to_flavor','thinks_recipe_is_flawed_due_to_technique_or_equipment','thinks_recipe_is_flawed_due_to_cooking_time','thinks_recipe_is_inauthentic','thinks_ingredients_hard_to_find']
neutral = ["user_responding_to_other_user","question","maybe_not_about_the_recipe"]

df_commenters = df_commenters.assign(
    Positive = lambda x: x[[col for col in positive if col in x.columns]].sum(axis=1),
    Negative = lambda x: x[[col for col in negative if col in x.columns]].sum(axis=1),
    Neutral  = lambda x: x[[col for col in neutral if col in x.columns]].sum(axis=1),
    posNegRatio = lambda x: x['Positive'] / x['Negative'].replace(0, np.nan)
)

df_commenters = df_commenters.merge(df_comment_recs, on='userID', how='right')
df_commenters = df_commenters.reset_index()
df_commenters

,userID,maybe_not_about_the_recipe,positive_user_describing_changes,positive_user_made_as_written,question,thinks_ingredients_hard_to_find,thinks_recipe_is_flawed_due_to_cooking_time,thinks_recipe_is_flawed_due_to_flavor,thinks_recipe_is_flawed_due_to_technique_or_equipment,thinks_recipe_is_inauthentic,user_responding_to_other_user,Positive,Negative,Neutral,posNegRatio,commentRecommendations
0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,1
1,1012,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
2,1016,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,NaN,1
3,2440,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0
4,2622,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54881,314458268,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0
54882,314502650,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0
54883,314699740,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,2
54884,314847038,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0
54885,315937775,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0

In [72]:
len(df_commenters)

54886

In [89]:
all_comments = ['Positive','Negative','Neutral']
df_commenters['totalComments'] = df_commenters[all_comments].sum(axis=1)
df_commenters

,userID,maybe_not_about_the_recipe,positive_user_describing_changes,positive_user_made_as_written,question,thinks_ingredients_hard_to_find,thinks_recipe_is_flawed_due_to_cooking_time,thinks_recipe_is_flawed_due_to_flavor,thinks_recipe_is_flawed_due_to_technique_or_equipment,thinks_recipe_is_inauthentic,user_responding_to_other_user,Positive,Negative,Neutral,posNegRatio,commentRecommendations,totalComments
0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,1,1.0
1,1012,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,1.0
2,1016,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,NaN,1,1.0
3,2440,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0,1.0
4,2622,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,38,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54881,314458268,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0,1.0
54882,314502650,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0,1.0
54883,314699740,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,2,1.0
54884,314847038,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0,1.0
54885,315937775,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0,1.0

In [64]:
df_negative_commenters = df_commenters.query('posNegRatio < 1')
len(df_negative_commenters)

9667

In [93]:
len(df_negative_commenters.query('totalComments > 1.39'))

1380

In [74]:
df_commenters.to_csv(os.path.join(export_dir, "df_commenters.csv"), index=False)

In [85]:
df_commenters_ranked = df_commenters.sort_values('commentRecommendations', ascending = False).reset_index()
df_commenters_ranked.query('userID == 193908654')

,index,userID,maybe_not_about_the_recipe,positive_user_describing_changes,positive_user_made_as_written,question,thinks_ingredients_hard_to_find,thinks_recipe_is_flawed_due_to_cooking_time,thinks_recipe_is_flawed_due_to_flavor,thinks_recipe_is_flawed_due_to_technique_or_equipment,thinks_recipe_is_inauthentic,user_responding_to_other_user,Positive,Negative,Neutral,posNegRatio,commentRecommendations
206,51775,193908654,0.0,1.0,1.0,0.0,0.0,0.0,3.0,2.0,2.0,0.0,2.0,7.0,0.0,0.285714,383

In [92]:
df_commenters['totalComments'].mean()

np.float64(1.397842801442991)

In [96]:
df_commenters.sort_values('commentRecommendations', ascending=False).query('totalComments > 2').head(10)

,userID,maybe_not_about_the_recipe,positive_user_describing_changes,positive_user_made_as_written,question,thinks_ingredients_hard_to_find,thinks_recipe_is_flawed_due_to_cooking_time,thinks_recipe_is_flawed_due_to_flavor,thinks_recipe_is_flawed_due_to_technique_or_equipment,thinks_recipe_is_inauthentic,user_responding_to_other_user,Positive,Negative,Neutral,posNegRatio,commentRecommendations,totalComments
30668,77345777,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,3.0,NaN,2391,5.0
14052,58439572,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,0.0,2380,3.0
6922,38686708,1.0,23.0,9.0,2.0,1.0,1.0,0.0,2.0,0.0,6.0,32.0,4.0,9.0,8.0,2273,45.0
39915,88387575,2.0,10.0,4.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,14.0,2.0,2.0,7.0,1719,18.0
42963,96369919,1.0,7.0,0.0,3.0,0.0,1.0,1.0,2.0,1.0,2.0,7.0,5.0,6.0,1.4,1501,18.0
32966,79269053,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,NaN,1476,7.0
4726,26414692,1.0,7.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,9.0,2.0,3.0,4.5,1359,14.0
20422,66080367,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,NaN,1325,7.0
51925,197104721,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,0.0,0.5,1291,3.0
42674,95216395,0.0,8.0,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,8.0,1.0,4.0,8.0,1211,13.0

### (df_commenters) Biggest Haters

In [22]:
df_65537845 = df.query('userID == 65537845')
df_65537845.to_csv(os.path.join(export_dir, "df_65537845_HATER.csv"), index=False)

In [23]:
df_193908654 = df.query('userID == 193908654')
df_193908654.to_csv(os.path.join(export_dir, "df_193908654_HATER.csv"), index=False)

In [24]:
df_97618752 = df.query('userID == 97618752')
df_97618752.to_csv(os.path.join(export_dir, "df_976187524_HATER.csv"), index=False)
df_97618752

,index,author,url,recipeTitle,commentBody,commentType,userID,commentRecommendations,ai_guess,recipeScore,numberOfRatings,sentiment,readable_ai_guess
7986,12,Vaughn Vreeland,https://cooking.nytimes.com/recipes/762791174-...,Cranberry-Cookie Butter Cheesecake Recipe (wit...,I dont get all the rave reviews. The cheesecak...,comment,97618752,1,thinks_recipe_is_flawed_due_to_technique_or_eq...,5,569,negative,Didn't like recipe due to technique or equipment
8039,12,Vaughn Vreeland,https://cooking.nytimes.com/recipes/762791174-...,Cranberry-Cookie Butter Cheesecake Recipe (wit...,Wouldnt make those again. Didn’t really taste ...,comment,97618752,0,thinks_recipe_is_flawed_due_to_flavor,5,569,negative,Didn't like recipe due to flavor
8794,20,Vaughn Vreeland,https://cooking.nytimes.com/recipes/1026584-tr...,Triple-Chocolate Brownies Recipe,Loved the taste but they came out hard by time...,comment,97618752,0,thinks_recipe_is_flawed_due_to_cooking_time,5,503,negative,Thought the cooking times were wrong
48968,38,Sohla El-Waylly,https://cooking.nytimes.com/recipes/1022676-br...,Brown-Butter Toffee Sandwich Cookies Recipe,"Ok first, cookies are amazing. Second, these a...",comment,97618752,28,thinks_recipe_is_flawed_due_to_technique_or_eq...,4,696,negative,Didn't like recipe due to technique or equipment
76188,40,Claire Saffitz,https://cooking.nytimes.com/recipes/1022272-st...,Strawberry and Cream Layer Cake Recipe,So basic. If this is the best cake you ever ma...,comment,97618752,0,thinks_recipe_is_flawed_due_to_flavor,4,"2,471",negative,Didn't like recipe due to flavor

### (df_recipes) Comment categories per recipe

In [25]:
url_map = df.set_index('recipeTitle')['url'].to_dict()

df_recipes = df.groupby('recipeTitle')['ai_guess'].value_counts().unstack().fillna(0)
total_comments = df_recipes.sum(axis=1)
df_recipes = df.groupby('recipeTitle')['ai_guess'].value_counts(normalize=True).unstack().fillna(0)
df_recipes['url'] = df_recipes.index.map(url_map)
df_recipes['totalComments'] = total_comments
df_recipe_sentiment = df.groupby('recipeTitle')['sentiment'].value_counts(normalize=True).unstack()
df_recipe_sentiment = df_recipe_sentiment.assign(posNegRatio=lambda df: df.positive/df.negative)
df_recipes = df_recipes.merge(df_recipe_sentiment, left_on='recipeTitle', right_index=True, how='left')
df_recipes = df_recipes.reset_index()

In [26]:
df_recipes.to_csv(os.path.join(export_dir, "df_recipes.csv"), index=False)

### (df_recipes) Recipes where more positive comments made it as written

In [27]:
df_by_the_book = df_recipes.query('positive_user_describing_changes < positive_user_made_as_written').sort_values('positive_user_describing_changes', ascending=False).reset_index()
df_by_the_book

,index,recipeTitle,maybe_not_about_the_recipe,positive_user_describing_changes,positive_user_made_as_written,question,thinks_ingredients_hard_to_find,thinks_recipe_is_flawed_due_to_cooking_time,thinks_recipe_is_flawed_due_to_flavor,thinks_recipe_is_flawed_due_to_technique_or_equipment,thinks_recipe_is_inauthentic,user_responding_to_other_user,url,totalComments,negative,neutral,positive,posNegRatio
0,375,Hamburger Buns Recipe,0.050000,0.300000,0.350000,0.100000,0.000000,0.100000,0.000000,0.100000,0.000000,0.000000,https://cooking.nytimes.com/recipes/1022247-ha...,20.0,0.200000,0.150000,0.650000,3.250000
1,695,Salmon Ssam Recipe,0.000000,0.266667,0.466667,0.200000,0.000000,0.000000,0.000000,0.066667,0.000000,0.000000,https://cooking.nytimes.com/recipes/770670821-...,15.0,0.066667,0.200000,0.733333,11.000000
2,119,Caramelized Brussels Sprouts With Lemon Recipe,0.060606,0.242424,0.272727,0.212121,0.000000,0.030303,0.060606,0.121212,0.000000,0.000000,https://cooking.nytimes.com/recipes/1024796-ca...,33.0,0.212121,0.272727,0.515152,2.428571
3,136,Chantilly Lili Recipe,0.180000,0.240000,0.340000,0.120000,0.000000,0.000000,0.060000,0.040000,0.000000,0.020000,https://cooking.nytimes.com/recipes/1026698-ch...,50.0,0.100000,0.320000,0.580000,5.800000
4,483,Mashed ‘Ulu With Passion Fruit Chutney Recipe,0.200000,0.200000,0.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,https://cooking.nytimes.com/recipes/1026156-ma...,5.0,NaN,0.200000,0.800000,NaN
5,521,Nihari (Spiced Oxtail Stew) Recipe,0.000000,0.181818,0.272727,0.454545,0.000000,0.000000,0.000000,0.090909,0.000000,0.000000,https://cooking.nytimes.com/recipes/1023957-ni...,11.0,0.090909,0.454545,0.454545,5.000000
6,439,Kimchi Napjak Mandu (Flat Dumplings) Recipe,0.125000,0.166667,0.250000,0.208333,0.041667,0.000000,0.000000,0.208333,0.000000,0.000000,https://cooking.nytimes.com/recipes/1026451-ki...,24.0,0.250000,0.333333,0.416667,1.666667
7,704,Salvadoran Quesadilla Recipe,0.142857,0.142857,0.285714,0.214286,0.000000,0.071429,0.071429,0.000000,0.071429,0.000000,https://cooking.nytimes.com/recipes/1025463-sa...,14.0,0.214286,0.357143,0.428571,2.000000
8,150,Chew Bread Recipe,0.066667,0.133333,0.266667,0.266667,0.000000,0.133333,0.066667,0.066667,0.000000,0.000000,https://cooking.nytimes.com/recipes/1025208-ch...,15.0,0.266667,0.333333,0.400000,1.500000
9,190,Chocolate Soufflés Recipe,0.100000,0.125000,0.150000,0.400000,0.000000,0.025000,0.050000,0.075000,0.000000,0.075000,https://cooking.nytimes.com/recipes/1023550-ch...,40.0,0.150000,0.575000,0.275000,1.833333
10,679,Rosca de Reyes Recipe,0.000000,0.125000,0.250000,0.000000,0.125000,0.000000,0.000000,0.125000,0.375000,0.000000,https://cooking.nytimes.com/recipes/1024954-ro...,8.0,0.625000,NaN,0.375000,0.600000
11,446,Laminated Pie Dough Recipe,0.065217,0.086957,0.173913,0.326087,0.000000,0.021739,0.021739,0.282609,0.000000,0.021739,https://cooking.nytimes.com/recipes/1026350-la...,46.0,0.326087,0.413043,0.260870,0.800000
12,257,Devil's Food White-Out Cake Recipe,0.066667,0.066667,0.133333,0.333333,0.000000,0.066667,0.200000,0.133333,0.000000,0.000000,https://cooking.nytimes.com/recipes/1015545-de...,15.0,0.400000,0.400000,0.200000,0.500000
13,185,Chocolate Fudge Recipe,0.055556,0.055556,0.111111,0.083333,0.083333,0.111111,0.055556,0.333333,0.000000,0.111111,https://cooking.nytimes.com/recipes/1023718-ch...,36.0,0.583333,0.250000,0.166667,0.285714
14,55,Blood Orange Gelato Recipe,0.000000,0.000000,0.117647,0.235294,0.000000,0.000000,0.000000,0.235294,0.117647,0.294118,https://cooking.nytimes.com/recipes/1027736-bl...,17.0,0.352941,0.529412,0.117647,0.333333
15,598,Piparkakut Recipe,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,https://cooking.nytimes.com/recipes/1013393-pi...,4.0,NaN,NaN,1.000000,NaN
16,914,Whipped Cream Cheese With Mentaiko Recipe,0.000000,0.000000,0.250000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,https://cooking.nytimes.com/recipes/1024293-wh...,4.0,NaN,0.750000,0.250000,NaN

In [28]:
df_by_the_book.to_csv(os.path.join(export_dir, "df_by_the_book.csv"), index=False)

### (df_recipes) Recipe rating versus number of positive comments

In [29]:
df_recipe_sentiment = df.groupby('recipeTitle')['sentiment'].value_counts(normalize=True).unstack()
df_recipe_sentiment.reset_index()

sentiment,recipeTitle,negative,neutral,positive
0,1-2-3-4 Cake Recipe,0.115385,0.423077,0.461538
1,1-2-3-4 Cake With Mocha Buttercream Recipe,0.333333,0.476190,0.190476
2,7Up Cake Recipe,0.229630,0.318519,0.451852
3,Aglio e Olio Baked Potatoes Recipe,0.120690,0.258621,0.620690
4,Air-Fryer Cheesecake Recipe,0.093333,0.333333,0.573333
...,...,...,...,...
929,Zucchini Pasta With Crispy Capers and Pistachi...,0.280374,0.149533,0.570093
930,Zucchini and Fennel Salad Recipe,0.200000,0.066667,0.733333
931,Çilbir (Turkish Eggs With Yogurt) Recipe,0.059829,0.059829,0.880342
932,Ìlá (Okra Soup With Shrimp and Greens) Recipe,0.357143,0.428571,0.214286
933,Ọbẹ̀ Onírù (Designer Stew) Recipe,NaN,1.000000,NaN

In [30]:
df_recipe_sentiment['recipeScore'] = df.groupby('recipeTitle')['recipeScore'].first()
df_recipe_sentiment['recipeScore'] = pd.to_numeric(df_recipe_sentiment['recipeScore'])
df_recipe_sentiment['recipeTitle'] = df.groupby('recipeTitle')['recipeTitle'].first()
df_recipe_sentiment['url'] = df.groupby('recipeTitle')['url'].first()
df_recipe_sentiment['recipeScore'].value_counts().reset_index()
df_recipe_sentiment

sentiment,negative,neutral,positive,recipeScore,recipeTitle,url
recipeTitle,,,,,,
1-2-3-4 Cake Recipe,0.115385,0.423077,0.461538,4.0,1-2-3-4 Cake Recipe,https://cooking.nytimes.com/recipes/1015491-1-...
1-2-3-4 Cake With Mocha Buttercream Recipe,0.333333,0.476190,0.190476,4.0,1-2-3-4 Cake With Mocha Buttercream Recipe,https://cooking.nytimes.com/recipes/1027370-1-...
7Up Cake Recipe,0.229630,0.318519,0.451852,4.0,7Up Cake Recipe,https://cooking.nytimes.com/recipes/1020510-7u...
Aglio e Olio Baked Potatoes Recipe,0.120690,0.258621,0.620690,5.0,Aglio e Olio Baked Potatoes Recipe,https://cooking.nytimes.com/recipes/1026385-ag...
Air-Fryer Cheesecake Recipe,0.093333,0.333333,0.573333,4.0,Air-Fryer Cheesecake Recipe,https://cooking.nytimes.com/recipes/1022925-ai...
...,...,...,...,...,...,...
Zucchini Pasta With Crispy Capers and Pistachios Recipe,0.280374,0.149533,0.570093,4.0,Zucchini Pasta With Crispy Capers and Pistachi...,https://cooking.nytimes.com/recipes/1024237-zu...
Zucchini and Fennel Salad Recipe,0.200000,0.066667,0.733333,5.0,Zucchini and Fennel Salad Recipe,https://cooking.nytimes.com/recipes/1026890-zu...
Çilbir (Turkish Eggs With Yogurt) Recipe,0.059829,0.059829,0.880342,5.0,Çilbir (Turkish Eggs With Yogurt) Recipe,https://cooking.nytimes.com/recipes/1024227-ci...
Ìlá (Okra Soup With Shrimp and Greens) Recipe,0.357143,0.428571,0.214286,4.0,Ìlá (Okra Soup With Shrimp and Greens) Recipe,https://cooking.nytimes.com/recipes/780328968-...
Ọbẹ̀ Onírù (Designer Stew) Recipe,NaN,1.000000,NaN,5.0,Ọbẹ̀ Onírù (Designer Stew) Recipe,https://cooking.nytimes.com/recipes/1027553-b-...

In [31]:
df_recipe_sentiment['posNegRatio'] = df_recipe_sentiment.positive / df_recipe_sentiment.negative
df_recipe_sentiment['totalComments'] = total_comments
df_recipe_sentiment

sentiment,negative,neutral,positive,recipeScore,recipeTitle,url,posNegRatio,totalComments
recipeTitle,,,,,,,,
1-2-3-4 Cake Recipe,0.115385,0.423077,0.461538,4.0,1-2-3-4 Cake Recipe,https://cooking.nytimes.com/recipes/1015491-1-...,4.000000,26.0
1-2-3-4 Cake With Mocha Buttercream Recipe,0.333333,0.476190,0.190476,4.0,1-2-3-4 Cake With Mocha Buttercream Recipe,https://cooking.nytimes.com/recipes/1027370-1-...,0.571429,21.0
7Up Cake Recipe,0.229630,0.318519,0.451852,4.0,7Up Cake Recipe,https://cooking.nytimes.com/recipes/1020510-7u...,1.967742,135.0
Aglio e Olio Baked Potatoes Recipe,0.120690,0.258621,0.620690,5.0,Aglio e Olio Baked Potatoes Recipe,https://cooking.nytimes.com/recipes/1026385-ag...,5.142857,58.0
Air-Fryer Cheesecake Recipe,0.093333,0.333333,0.573333,4.0,Air-Fryer Cheesecake Recipe,https://cooking.nytimes.com/recipes/1022925-ai...,6.142857,75.0
...,...,...,...,...,...,...,...,...
Zucchini Pasta With Crispy Capers and Pistachios Recipe,0.280374,0.149533,0.570093,4.0,Zucchini Pasta With Crispy Capers and Pistachi...,https://cooking.nytimes.com/recipes/1024237-zu...,2.033333,107.0
Zucchini and Fennel Salad Recipe,0.200000,0.066667,0.733333,5.0,Zucchini and Fennel Salad Recipe,https://cooking.nytimes.com/recipes/1026890-zu...,3.666667,30.0
Çilbir (Turkish Eggs With Yogurt) Recipe,0.059829,0.059829,0.880342,5.0,Çilbir (Turkish Eggs With Yogurt) Recipe,https://cooking.nytimes.com/recipes/1024227-ci...,14.714286,117.0
Ìlá (Okra Soup With Shrimp and Greens) Recipe,0.357143,0.428571,0.214286,4.0,Ìlá (Okra Soup With Shrimp and Greens) Recipe,https://cooking.nytimes.com/recipes/780328968-...,0.600000,14.0
Ọbẹ̀ Onírù (Designer Stew) Recipe,NaN,1.000000,NaN,5.0,Ọbẹ̀ Onírù (Designer Stew) Recipe,https://cooking.nytimes.com/recipes/1027553-b-...,NaN,3.0

In [32]:
df_combined = pd.concat([df_recipes, df_recipe_sentiment])
df_combined

,recipeTitle,maybe_not_about_the_recipe,positive_user_describing_changes,positive_user_made_as_written,question,thinks_ingredients_hard_to_find,thinks_recipe_is_flawed_due_to_cooking_time,thinks_recipe_is_flawed_due_to_flavor,thinks_recipe_is_flawed_due_to_technique_or_equipment,thinks_recipe_is_inauthentic,user_responding_to_other_user,url,totalComments,negative,neutral,positive,posNegRatio,recipeScore
0,1-2-3-4 Cake Recipe,0.115385,0.461538,0.000000,0.307692,0.000000,0.000000,0.000000,0.115385,0.000000,0.000000,https://cooking.nytimes.com/recipes/1015491-1-...,26.0,0.115385,0.423077,0.461538,4.000000,NaN
1,1-2-3-4 Cake With Mocha Buttercream Recipe,0.142857,0.095238,0.095238,0.285714,0.047619,0.000000,0.142857,0.142857,0.000000,0.047619,https://cooking.nytimes.com/recipes/1027370-1-...,21.0,0.333333,0.476190,0.190476,0.571429,NaN
2,7Up Cake Recipe,0.088889,0.437037,0.014815,0.148148,0.000000,0.029630,0.133333,0.066667,0.000000,0.081481,https://cooking.nytimes.com/recipes/1020510-7u...,135.0,0.229630,0.318519,0.451852,1.967742,NaN
3,Aglio e Olio Baked Potatoes Recipe,0.068966,0.396552,0.224138,0.189655,0.017241,0.017241,0.017241,0.034483,0.034483,0.000000,https://cooking.nytimes.com/recipes/1026385-ag...,58.0,0.120690,0.258621,0.620690,5.142857,NaN
4,Air-Fryer Cheesecake Recipe,0.053333,0.453333,0.120000,0.240000,0.000000,0.013333,0.026667,0.053333,0.000000,0.040000,https://cooking.nytimes.com/recipes/1022925-ai...,75.0,0.093333,0.333333,0.573333,6.142857,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zucchini Pasta With Crispy Capers and Pistachios Recipe,Zucchini Pasta With Crispy Capers and Pistachi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cooking.nytimes.com/recipes/1024237-zu...,107.0,0.280374,0.149533,0.570093,2.033333,4.0
Zucchini and Fennel Salad Recipe,Zucchini and Fennel Salad Recipe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cooking.nytimes.com/recipes/1026890-zu...,30.0,0.200000,0.066667,0.733333,3.666667,5.0
Çilbir (Turkish Eggs With Yogurt) Recipe,Çilbir (Turkish Eggs With Yogurt) Recipe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cooking.nytimes.com/recipes/1024227-ci...,117.0,0.059829,0.059829,0.880342,14.714286,5.0
Ìlá (Okra Soup With Shrimp and Greens) Recipe,Ìlá (Okra Soup With Shrimp and Greens) Recipe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cooking.nytimes.com/recipes/780328968-...,14.0,0.357143,0.428571,0.214286,0.600000,4.0
Ọbẹ̀ Onírù (Designer Stew) Recipe,Ọbẹ̀ Onírù (Designer Stew) Recipe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cooking.nytimes.com/recipes/1027553-b-...,3.0,NaN,1.000000,NaN,NaN,5.0

In [33]:
df_recipe_sentiment.to_csv(os.path.join(export_dir, "df_recipe_sentiment.csv"), index=False)

### (df_authors) Comment category totals by author:

In [126]:
df.groupby('author')['recipeTitle'].nunique()

author
Alexa Weibel         48
Ali Slagle           45
Christina Morales    27
Claire Saffitz       48
David Tanis          39
Emily Weinstein      36
Eric Kim             48
Genevieve Ko         48
Julia Moskin         48
Kay Chun             48
Kenji López-Alt      48
Kim Severson         21
Korsha Wilson        29
Ligaya Mishan        48
Lisa Donovan         28
Melissa Clark        48
Priya Krishna        48
Sam Sifton           48
Sohla El-Waylly      45
Tanya Sichynsky       4
Vaughn Vreeland      44
Yewande Komolafe     45
Yotam Ottolenghi     48
Name: recipeTitle, dtype: int64

In [128]:
df_48_authors = df.groupby('author').filter(lambda x: x['recipeTitle'].nunique() >= 48)
df_48_authors

,index,author,url,recipeTitle,commentBody,commentType,userID,commentRecommendations,ai_guess,recipeScore,numberOfRatings,sentiment,readable_ai_guess
0,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Delicious! I would suggest maybe letting the m...,comment,15548414,325,thinks_recipe_is_flawed_due_to_technique_or_eq...,5,791,negative,Didn't like recipe due to technique or equipment
1,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"I cooked the brisket, with all the Bulgogi ing...",comment,71133436,137,positive_user_describing_changes,5,791,positive,Liked recipe but made changes
2,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,I used flank steak b/c the Wegman's I went to ...,comment,57060720,70,positive_user_describing_changes,5,791,positive,Liked recipe but made changes
3,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,"For my vegetarian household, I substituted sei...",comment,65782933,62,positive_user_describing_changes,5,791,positive,Liked recipe but made changes
4,0,Sam Sifton,https://cooking.nytimes.com/recipes/1014203-bu...,Bulgogi Sliders With Scallion Salsa Recipe,Put the whole piece of brisket in the freezer ...,comment,72381463,46,maybe_not_about_the_recipe,5,791,neutral,Off-topic
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76717,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Froze half after shaping before the last proof...,comment,232304210,0,positive_user_describing_changes,5,335,positive,Liked recipe but made changes
76718,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,Thank you Claire. I’m on my 6 try at perfectin...,comment,176541269,0,positive_user_made_as_written,5,335,positive,Liked recipe and prepared as written
76719,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,This turned out so well!! For the final proof ...,comment,224292953,0,positive_user_describing_changes,5,335,positive,Liked recipe but made changes
76720,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,First time attempting a puff pastry and it tur...,comment,72466649,0,positive_user_made_as_written,5,335,positive,Liked recipe and prepared as written
76721,47,Claire Saffitz,https://cooking.nytimes.com/recipes/1022057-pa...,Pain au Chocolat Recipe,These are delicious! They have come out perfec...,comment,59884695,0,positive_user_describing_changes,5,335,positive,Liked recipe but made changes

In [129]:
df_comments_by_author = df_48_authors['author'].value_counts().reset_index()
df_comments_by_author.columns = ['author', 'count']
pd.to_numeric(df_comments_by_author['count'])
df_comments_by_author

              author  count
0         Sam Sifton   7280
1       Alexa Weibel   6058
2    Kenji López-Alt   5248
3       Genevieve Ko   5010
4      Priya Krishna   4935
5      Melissa Clark   4481
6       Julia Moskin   3738
7     Claire Saffitz   3714
8   Yotam Ottolenghi   3660
9           Eric Kim   3544
10          Kay Chun   2834
11     Ligaya Mishan   2093

In [130]:
df_comments_by_author.to_csv(os.path.join(export_dir, "df_comments_by_author.csv"), index=False)

### (df_authors) Individual category counts by author

In [35]:
df_category_counts_by_author = df.groupby('author')['ai_guess'].value_counts().unstack()
df_category_counts_by_author['totalComments'] = df_category_counts_by_author.sum(axis=1)
df_category_counts_by_author = df_category_counts_by_author.reset_index()
df_category_counts_by_author

ai_guess,author,maybe_not_about_the_recipe,positive_user_describing_changes,positive_user_made_as_written,question,thinks_ingredients_hard_to_find,thinks_recipe_is_flawed_due_to_cooking_time,thinks_recipe_is_flawed_due_to_flavor,thinks_recipe_is_flawed_due_to_technique_or_equipment,thinks_recipe_is_inauthentic,user_responding_to_other_user,totalComments
0,Alexa Weibel,194,3438,699,630,39,169,358,375,38,118,6058
1,Ali Slagle,124,1547,240,388,6,76,286,140,10,79,2896
2,Christina Morales,58,346,71,139,17,20,62,40,35,54,842
3,Claire Saffitz,164,1303,522,785,30,129,194,448,20,119,3714
4,David Tanis,43,547,100,251,8,27,103,103,17,43,1242
5,Emily Weinstein,56,1010,192,250,2,131,127,134,10,22,1934
6,Eric Kim,194,1530,399,695,29,126,158,286,37,90,3544
7,Genevieve Ko,276,2340,474,827,52,152,293,384,32,180,5010
8,Julia Moskin,197,1803,293,470,27,124,332,324,72,96,3738
9,Kay Chun,85,1578,251,355,20,87,234,126,30,68,2834
10,Kenji López-Alt,365,2416,703,682,35,72,374,405,66,130,5248
11,Kim Severson,47,537,82,106,13,15,42,44,6,12,904
12,Korsha Wilson,71,350,78,140,9,23,54,65,20,25,835
13,Ligaya Mishan,169,852,180,389,61,34,177,107,39,85,2093
14,Lisa Donovan,188,817,182,420,38,75,171,160,49,106,2206
15,Melissa Clark,272,2046,407,795,21,117,331,314,34,144,4481
16,Priya Krishna,250,2494,423,663,41,135,359,352,66,152,4935
17,Sam Sifton,473,4471,617,632,74,153,352,270,66,172,7280
18,Sohla El-Waylly,203,2544,658,478,59,152,448,360,17,126,5045
19,Tanya Sichynsky,43,274,73,104,2,12,21,27,14,24,594
20,Vaughn Vreeland,299,2629,717,1028,29,200,422,558,30,157,6069
21,Yewande Komolafe,80,634,114,298,26,74,114,114,34,72,1560
22,Yotam Ottolenghi,125,1769,362,565,81,126,233,237,18,144,3660

In [36]:
df_category_counts_by_author.to_csv(os.path.join(export_dir, "df_category_counts_by_author.csv"), index=False)

In [37]:
df_category_percentages_by_author = df.groupby('author')['ai_guess'].value_counts(normalize=True).unstack().reset_index()
df_category_percentages_by_author

ai_guess,author,maybe_not_about_the_recipe,positive_user_describing_changes,positive_user_made_as_written,question,thinks_ingredients_hard_to_find,thinks_recipe_is_flawed_due_to_cooking_time,thinks_recipe_is_flawed_due_to_flavor,thinks_recipe_is_flawed_due_to_technique_or_equipment,thinks_recipe_is_inauthentic,user_responding_to_other_user
0,Alexa Weibel,0.032024,0.567514,0.115385,0.103995,0.006438,0.027897,0.059095,0.061902,0.006273,0.019478
1,Ali Slagle,0.042818,0.534185,0.082873,0.133978,0.002072,0.026243,0.098757,0.048343,0.003453,0.027279
2,Christina Morales,0.068884,0.410926,0.084323,0.165083,0.020190,0.023753,0.073634,0.047506,0.041568,0.064133
3,Claire Saffitz,0.044157,0.350835,0.140549,0.211362,0.008078,0.034733,0.052235,0.120625,0.005385,0.032041
4,David Tanis,0.034622,0.440419,0.080515,0.202093,0.006441,0.021739,0.082931,0.082931,0.013688,0.034622
5,Emily Weinstein,0.028956,0.522234,0.099276,0.129266,0.001034,0.067735,0.065667,0.069286,0.005171,0.011375
6,Eric Kim,0.054740,0.431716,0.112585,0.196106,0.008183,0.035553,0.044582,0.080700,0.010440,0.025395
7,Genevieve Ko,0.055090,0.467066,0.094611,0.165070,0.010379,0.030339,0.058483,0.076647,0.006387,0.035928
8,Julia Moskin,0.052702,0.482343,0.078384,0.125736,0.007223,0.033173,0.088818,0.086677,0.019262,0.025682
9,Kay Chun,0.029993,0.556810,0.088567,0.125265,0.007057,0.030699,0.082569,0.044460,0.010586,0.023994
10,Kenji López-Alt,0.069550,0.460366,0.133956,0.129954,0.006669,0.013720,0.071265,0.077172,0.012576,0.024771
11,Kim Severson,0.051991,0.594027,0.090708,0.117257,0.014381,0.016593,0.046460,0.048673,0.006637,0.013274
12,Korsha Wilson,0.085030,0.419162,0.093413,0.167665,0.010778,0.027545,0.064671,0.077844,0.023952,0.029940
13,Ligaya Mishan,0.080745,0.407071,0.086001,0.185858,0.029145,0.016245,0.084568,0.051123,0.018634,0.040612
14,Lisa Donovan,0.085222,0.370354,0.082502,0.190390,0.017226,0.033998,0.077516,0.072529,0.022212,0.048051
15,Melissa Clark,0.060701,0.456595,0.090828,0.177416,0.004686,0.026110,0.073867,0.070074,0.007588,0.032136
16,Priya Krishna,0.050659,0.505370,0.085714,0.134347,0.008308,0.027356,0.072746,0.071327,0.013374,0.030800
17,Sam Sifton,0.064973,0.614148,0.084753,0.086813,0.010165,0.021016,0.048352,0.037088,0.009066,0.023626
18,Sohla El-Waylly,0.040238,0.504262,0.130426,0.094747,0.011695,0.030129,0.088801,0.071358,0.003370,0.024975
19,Tanya Sichynsky,0.072391,0.461279,0.122896,0.175084,0.003367,0.020202,0.035354,0.045455,0.023569,0.040404
20,Vaughn Vreeland,0.049267,0.433185,0.118141,0.169385,0.004778,0.032954,0.069534,0.091943,0.004943,0.025869
21,Yewande Komolafe,0.051282,0.406410,0.073077,0.191026,0.016667,0.047436,0.073077,0.073077,0.021795,0.046154
22,Yotam Ottolenghi,0.034153,0.483333,0.098907,0.154372,0.022131,0.034426,0.063661,0.064754,0.004918,0.039344

In [38]:
df_category_percentages_by_author.to_csv(os.path.join(export_dir, "df_category_percentages_by_author.csv"), index=False)

### (df) Exports to csv

In [8]:
df.to_csv(os.path.join(export_dir, "df.csv"), index=False)

In [9]:
df.head(50).to_csv(os.path.join(export_dir, "df_preview.csv"), index=False)

In [10]:
df_recipe_highlight_01 = df[df['author'] == 'Sam Sifton']
df_recipe_highlight_01 = df_recipe_highlight_01[df_recipe_highlight_01['index'] == 20]
df_recipe_highlight_01.to_csv(os.path.join(export_dir, "df_recipe_theStoresGreenDip.csv"), index=False)

In [11]:
print(df_recipe_highlight_01['url'])
pd.set_option('display.max_colwidth', None)

3630    https://cooking.nytimes.com/recipes/1020427-th...
3631    https://cooking.nytimes.com/recipes/1020427-th...
3632    https://cooking.nytimes.com/recipes/1020427-th...
3633    https://cooking.nytimes.com/recipes/1020427-th...
3634    https://cooking.nytimes.com/recipes/1020427-th...
                              ...
3769    https://cooking.nytimes.com/recipes/1020427-th...
3770    https://cooking.nytimes.com/recipes/1020427-th...
3771    https://cooking.nytimes.com/recipes/1020427-th...
3772    https://cooking.nytimes.com/recipes/1020427-th...
3773    https://cooking.nytimes.com/recipes/1020427-th...
Name: url, Length: 144, dtype: str

In [21]:
df_recipe_laminated_pie_dough_comments = df.query('url == "https://cooking.nytimes.com/recipes/1026350-laminated-pie-dough"')

In [22]:
df_recipe_laminated_pie_dough_comments.to_csv(os.path.join(export_dir, "df_recipe_laminated_pie_dough_comments.csv"), index=False)

In [24]:
df_recipe_suspiro = df.query('url == "https://cooking.nytimes.com/recipes/1025030-suspiro-a-la-limena-caramel-pudding-with-port-meringue"')

In [25]:
df_recipe_suspiro.to_csv(os.path.join(export_dir, "df_recipe_suspiro.csv"), index=False)

In [26]:
df_recipe_yorkshire = df.query('url == "https://cooking.nytimes.com/recipes/1022817-vegan-yorkshire-puddings"')

In [27]:
df_recipe_yorkshire.to_csv(os.path.join(export_dir, "df_recipe_yorkshire.csv"), index=False)

In [28]:
df_recipe_bars = df.query('url == "https://cooking.nytimes.com/recipes/1023798-banana-nut-breakfast-bars"')
df_recipe_bars.to_csv(os.path.join(export_dir, "df_recipe_bars.csv"), index=False)

In [99]:
df_recipe_salad = df.query('url == "https://cooking.nytimes.com/recipes/1024570-green-salad-with-warm-goat-cheese-salade-de-chevre-chaud"')
df_recipe_salad.to_csv(os.path.join(export_dir, "df_recipe_salad.csv"), index=False)

In [43]:
df_recipe_pastaRundown = df.query('url == "https://cooking.nytimes.com/recipes/765313321-pasta-in-rundown-sauce"')
df_recipe_pastaRundown.to_csv(os.path.join(export_dir, "df_recipe_pastaRundown.csv"), index=False)

In [45]:
df_recipe_pastaRundown['ai_guess'].value_counts()

ai_guess
positive_user_describing_changes                         11
thinks_recipe_is_flawed_due_to_flavor                     7
question                                                  5
thinks_recipe_is_flawed_due_to_cooking_time               4
thinks_recipe_is_inauthentic                              3
maybe_not_about_the_recipe                                2
positive_user_made_as_written                             2
thinks_recipe_is_flawed_due_to_technique_or_equipment     2
user_responding_to_other_user                             1
Name: count, dtype: int64

### Test plots

In [ ]:
df_recipe_sentiment.plot.scatter(x='positive',y='recipeScore')

In [ ]:
df_recipe_sentiment.plot.scatter(x='negative',y='recipeScore')

In [ ]:
df_recipe_sentiment.plot.scatter(x='neutral',y='recipeScore')